Change Command: random_items
harbingerofme/DebugToolkit pull request #136
Opened 2023-04-28 09:54 UTC by SChinchi

**Which Command**
`random_items`

**What should it do?**
Update the command to also include lunar and void items. I had two options for parsing and I chose the first:

1. Expect only "lunar", "void", or "both". It's cleaner for now, but may be a nightmare to maintain if it ever supports more tiers.
2. Check whether the argument string contains "lunar" and/or "void". Easier to maintain for more tiers, but it also allows "garbage_lunar_garbage_void" to parse correctly and makes it impossible to tell whether "lunawr" is a typo or garbage.

I also patched `Inventory.GiveRandomItems` because Hopoo had some copy/paste fun with the void tiers.

2023-04-28 14:08 UTC, xiaoxiao921 commented on Code/Hooks.cs
> +                Debug.LogWarning("Unable to patch RoR2.Inventory.GiveRandomItems");
let's use a bepinex logger

2023-04-28 14:13 UTC, xiaoxiao921 commented on Code/DT-Commands/Items.cs
> +                    case "both":
not a fan of this, how about "all" instead and allowing the user for comma separated entries?
`random_items lunar,customTier,void`
`random_items all`
i'd probably move away from the random items HG function alltogether and roll our own which support ItemTierDef (it has a name field)

2023-04-28 14:14 UTC, xiaoxiao921 commented
none is a idea

2023-04-28 14:38 UTC, SChinchi commented on Code/DT-Commands/Items.cs
> +                    case "both":
That's a good idea. We can probably do with a `list_itemtiers` command in that case as well. The question is what we do about tier weighting. Generating white and red items with the same frequency seems a bit silly. Maybe `random_items tier1:weight1,tier2:weight2`? It does get wordy very quickly though. Then again it depends what we want out of that command. I've rarely used it myself and without knowing the history of the mod I assume it was added just because the HG method exists.

2023-04-28 14:41 UTC, xiaoxiao921 commented on Code/DT-Commands/Items.cs
> +                    case "both":
Usage seems to be for simulating advanced mid / end game runs without having to do them from scratch, I'd say custom weighting can wait

2023-04-28 15:04 UTC, SChinchi commented on Code/DT-Commands/Items.cs
> +                    case "both":
Okay, let me summarise:

- remove the HG method patch
- add `list_itemtiers`
- change the command signature to `random_items {count} [tiers ('all'|any comma-separated tier names):'all'] [target]`. "none" as an option seems irrelevant here.
- the tier names probably have to match exactly, no partial matches due to Tier1/VoidTier1 and the unpredictability of custom tiers.
- for custom tiers the item pool must be built from the ItemCatalog.allItemDefs + ItemDef.IsAvailable unless I'm missing something.

2023-04-28 15:25 UTC, xiaoxiao921 commented on Code/DT-Commands/Items.cs
> +                    case "both":
Agree on the exact match, we'd keep ToLowerInvariant though in my opinion

For the custom tiers item pools weight i'm really not sure there, I don't think there is any consolidated way of handling them (I just realized that), it could be that people hijack existing drop table through ChestBehavior / BasicPickupDropTable

I can't think of a clean solution for this as every weight seems to be now handled through BasicPickupDropTable and are most likely totally different from an instance to another

2023-04-29 16:51 UTC, SChinchi commented on Code/DT-Commands/Items.cs
> +                    case "both":
I added the changed. I also decided to keep the match partial to keep with the theme of every other method. Besides, if you're doing `give_item focus` and you get a focus convergence instead of a focus crystal, that's on you.

The NoTier is excluded in all of this because there is no explicit ItemTierDef and we'd need to go out of our way to add it in for `list_itemtier`. Untiered items are also not in `ItemCatalog.allItems`, which is the biggest hassle of all. Lastly, getting a bunch of untiered items is probably not what someone has in mind when they use "all".

The command is now looking very sweet. Adding custom weights eventually will be chef's kiss, because at the moment the void items interfere with the other tiers.

2023-05-01 17:41 UTC, xiaoxiao921 requested changes

2023-05-01 17:41 UTC, xiaoxiao921 commented on Code/StringFinder.cs
> +                if (tierDef.name.ToUpper().Contains(name.ToUpper()))
UpperInvariant

2023-05-01 17:41 UTC, xiaoxiao921 commented on Code/DT-Commands/Items.cs
> +            if (args.Count < 2 || (args[1] == Lang.DEFAULT_VALUE || args[1].ToUpper() == Lang.ALL))
toUpperInvariant

2023-05-01 17:41 UTC, xiaoxiao921 commented on Code/StringFinder.cs
> +                else if (tierDef.name.ToUpper().Contains(name.ToUpper()))
UpperInvariant

2023-05-01 17:42 UTC, xiaoxiao921 commented
Very small nitpick about ToUpper conversion so that user lang doesnt come into play, looks good to me otherwise

2023-05-02 09:24 UTC, SChinchi commented
Good point about the invariant. From memor, the code is fairly inconsistent about that, where some of the list_ commands also use toupper. I'm also guilty in using that for pinged enemies for items/buff. I've only made the relevant changes here and I'll deal with the rest of the source code in a single PR.

2023-05-02 10:47 UTC, xiaoxiao921 approved these changes

2023-05-02 10:47 UTC, merged

2023-05-02 10:59 UTC, xiaoxiao921 commented
Actually I just realized we may want invariant or not depending if we matching against internal names or translated names, didn't really think that through / checked if what I asked earlier was correct