Improved autocompletion
harbingerofme/DebugToolkit pull request #177
Opened 2024-02-01 10:46 UTC by SChinchi

Improve autocompletion to apply for every argument in a command, featuring multiple aliases for each option, matching ordering, and match highlighting. The command signature now also appears above as a reminder while typing. The API is open to other mods to use!

The options prioritise strings that start with the input partial and/or matching as much as possible from the target string. The StringFinder partial matching methods have also been modified to behave similarly. This was previously mentioned as an alternative in #164 but it now makes more sense so both the autocompletion and matching/list methods return results in the same order. The director cards and interactables are an exception because the StringFinder methods use additional aliases compared to the dynamic variables of autocompletion, thereby altering the order of results. This is generally not a big deal since for most partial strings it's only the top results that counts.

Updated list query example
![listquery](https://github.com/harbingerofme/DebugToolkit/assets/57867641/323cad85-fbbd-4d61-a697-b26fd36f6a7d)

2024-03-04 16:43 UTC, xiaoxiao921 requested changes

2024-03-04 16:43 UTC, xiaoxiao921 commented on Code/AutoCompletion/AutoCompleteParser.cs
> +        }
- Don't use GetCallingAssembly but instead force the user to pass Assembly object
- GetTypes can throw, but the RoR2BepinexPack hook will kick in and save you
- Same thing for GetCustomAttributes, wrap it with an inner try catch inside the foreach, it can `throw` nasty things at you iirc

2024-03-04 16:54 UTC, SChinchi commented on Code/AutoCompletion/AutoCompleteParser.cs
> +        }
The reason for GetCallingAssembly was to ensure the scan is applied on the assembly the mod calls the API from, otherwise they'd have the freedom to pass any one. Am I wrong or have I misunderstood something else?

Fair points on the other two. I've just checked the documentation and I'll apply changes some time tomorrow (running low on time for today).

2024-03-04 17:01 UTC, harbingerofme commented on Code/AutoCompletion/AutoCompleteParser.cs
> +        }
with calling assembly no wrapper can be made around this

2024-03-04 17:04 UTC, xiaoxiao921 commented on Code/AutoCompletion/AutoCompleteParser.cs
> +        }
CallingAssembly have caused problems for us in the past, it's just cleaner to give control over exactly which assembly the user want it to be applied on, they just have to know a bit on how to pass their own Assembly but it's not that difficult if they just look around on google

2024-03-05 14:46 UTC, SChinchi commented on Code/AutoCompletion/AutoCompleteParser.cs
> +        }
Changes applied. It seems from the exception of GetTypes I can salvage at least the ones that succeeded in loading, but I didn't see anything similar for the attributes treatment.

2024-03-05 15:59 UTC, xiaoxiao921 approved these changes

2024-03-05 15:59 UTC, merged